### ISSUE TITLE
what is the license of the corpus provided?

### ISSUE THREAD

**Issue by ksmultiacc3** [dtuggener/LEDGAR_provision_classification#2]

**Comment by dtuggener** [comment]
EDGAR, which LEDGAR is based on, is a public database in the public domain, see:
https://www.sec.gov/edgar/about
The readme of the corpus (https://drive.switch.ch/index.php/s/j9S0GRMAbGZKa1A) states that we provide LEDGAR under the MIT licence (as well as the code on github).
